sonar.organization=europeana
sonar.projectKey=europeana_sea
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sources=packages/**/*
sonar.exclusions=packages/**/locales/*.json
sonar.tests=packages/**/*
sonar.test.inclusions=packages/**/*.spec.js
