sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.organization=europeana
sonar.projectKey=europeana_sea
sonar.sources=packages/apps/cats,packages/apps/ds4ch,packages/directives/vue-visible-on-scroll,packages/layers/base,packages/plugins/vue-contentful-graphql
sonar.tests=packages/apps/cats,packages/apps/ds4ch,packages/directives/vue-visible-on-scroll,packages/layers/base,packages/plugins/vue-contentful-graphql
sonar.exclusions=packages/apps/ds4ch/i18n/locales/*.json
sonar.test.inclusions=packages/**/*.spec.js
