import { afterAll, afterEach, describe, expect, it, vi } from "vitest";

import { runTask } from "./tasks.js";

const mocks = vi.hoisted(() => {
  return {
    fs: {
      mkdirSync: vi.fn(),
      rmSync: vi.fn(),
      writeFileSync: vi.fn(),
    },
    path: {
      resolve: vi.fn((path0, path1) => path1),
    },
  };
});

vi.mock(import("node:fs"), () => {
  return {
    default: {
      mkdirSync: mocks.fs.mkdirSync,
      rmSync: mocks.fs.rmSync,
      writeFileSync: mocks.fs.writeFileSync,
    },
  };
});

vi.mock(import("node:path"), () => {
  return {
    default: {
      resolve: mocks.path.resolve,
    },
  };
});

describe("@/tasks.js", () => {
  afterEach(() => {
    vi.clearAllMocks();
  });
  afterAll(() => {
    vi.restoreAllMocks();
  });

  describe("runTask", () => {
    describe("mkdir", () => {
      it("makes directory for the generated StyleJSON files", () => {
        runTask("mkdir", "versatiles");

        expect(mocks.fs.mkdirSync).toHaveBeenCalledTimes(1);
        expect(mocks.fs.mkdirSync).toHaveBeenCalledWith("../dist/versatiles", {
          recursive: true,
        });
      });
    });

    describe("clean", () => {
      it("removes directory for the generated StyleJSON files", () => {
        runTask("clean", "versatiles");

        expect(mocks.fs.rmSync).toHaveBeenCalledTimes(1);
        expect(mocks.fs.rmSync).toHaveBeenCalledWith("../dist/versatiles", {
          force: true,
          recursive: true,
        });
      });
    });

    describe("generate", () => {
      it("removes directory for the generated StyleJSON files", () => {
        runTask("generate", "versatiles");

        expect(mocks.fs.rmSync).toHaveBeenCalledTimes(1);
        expect(mocks.fs.rmSync).toHaveBeenCalledWith("../dist/versatiles", {
          force: true,
          recursive: true,
        });
      });

      it("makes directory for the generated StyleJSON files", () => {
        runTask("generate", "versatiles");

        expect(mocks.fs.mkdirSync).toHaveBeenCalledTimes(1);
        expect(mocks.fs.mkdirSync).toHaveBeenCalledWith("../dist/versatiles", {
          recursive: true,
        });
      });

      it("writes file for each generated by the style", () => {
        runTask("generate", "versatiles");

        expect(mocks.fs.writeFileSync).toHaveBeenCalledTimes(10);
      });
    });
  });
});
