name: CI (matrix)

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+.*'
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]
  workflow_dispatch:

jobs:
  ci-app:
    name: CI (app)
    strategy:
      fail-fast: false
      matrix:
        app: [ds4ch]
    uses: ./.github/workflows/ci-app.yml
    with:
      app: ${{ matrix.app }}
