name: "Lokalise: push"

on:
  # TODO: also commits to main
  workflow_dispatch:
    inputs:
      force:
        description: 'Force upload of all base language strings. (Lokalise "rambo" mode.)'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push files to Lokalise
        uses: lokalise/lokalise-push-action@v3.6.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: ${{ secrets.LOKALISE_PROJECT_ID }}
          file_format: json
          translations_path: packages/apps/ds4ch/i18n/locales
          base_lang: en_GB
          flat_naming: true
          rambo_mode: { { inputs.force } }
          additional_params: |
            --indentation=2sp
            --export-empty-as=skip
            --export-sort=a_z
            --replace-breaks=false
            --add-newline-eof=true
            --language-mapping=[{"original_language_iso":"en_GB","custom_language_iso":"en"},{"original_language_iso":"mt_MT","custom_language_iso":"mt"},{"original_language_iso":"ga_IE","custom_language_iso":"ga"}]
